# Generated by Django 3.2.12 on 2022-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alt_contact',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
