# Generated by Django 3.2.12 on 2022-02-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kwbat', 'kwbat'), ('ewbat', 'ewbat'), ('ball', 'ball'), ('batting gloves', 'batting gloves')], default='', max_length=15),
        ),
    ]
