# Generated by Django 3.2.12 on 2022-02-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='value',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
