# Generated by Django 3.2.12 on 2022-02-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_category_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Kashmir Willow Bat', 'Kashmir Willow Bat'), ('English Willow Bat', 'English Willow Bat'), ('Leather Ball', 'Leather Ball'), ('Batting Gloves', 'Batting Gloves')], default='', max_length=40),
        ),
    ]
