# Generated by Django 3.2.12 on 2022-03-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220331_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sleeves',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
