# Generated by Django 3.2.12 on 2022-03-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_stock_sleeves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sleeves',
            field=models.CharField(blank=True, choices=[('half_sleeves', 'half_sleeves'), ('full_sleeves', 'full_sleeves'), ('sleeveless', 'sleeveless')], default='', max_length=20, null=True),
        ),
    ]
