# Generated by Django 3.2.12 on 2022-02-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('kashmir_willow_bat', 'kashmir_willow_bat'), ('english_willow_bat', 'english_willow_bat'), ('leather_ball', 'leather_ball'), ('batting_gloves', 'batting_gloves')], default='', max_length=40),
        ),
    ]
