# Generated by Django 3.2.12 on 2022-02-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('starting_from', models.DateField()),
                ('expiring_on', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='', max_length=40)),
            ],
        ),
    ]
