# Generated by Django 3.2.12 on 2022-02-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_couponcode_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='message',
            field=models.CharField(default='Coupon Applied !', max_length=20),
        ),
    ]
