# Generated by Django 3.2.12 on 2022-02-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_couponcode_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='message',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='redeem_count',
            field=models.IntegerField(default=1),
        ),
    ]
