# Generated by Django 3.2.12 on 2022-02-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_couponcode_redeem_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='applicable_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.product'),
        ),
    ]
