# Generated by Django 3.2.12 on 2022-02-24 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_couponcode_applicable_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='applicable_on',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='applicable_on',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
        migrations.RemoveField(
            model_name='couponcode',
            name='redeem_by',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='redeem_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
