# Generated by Django 3.2.12 on 2022-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220224_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='expiring_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='starting_from',
            field=models.DateTimeField(),
        ),
    ]
