# Generated by Django 3.2.12 on 2022-03-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20220226_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addr1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='addr2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='alt_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
    ]
